###
---
- name: 'Prepare image'
  hosts: default
  become: true

  tasks:
    - name: add path to ~/.bashrc
      command: echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
    - name: install pip and ruby
      command: sudo apt-get install python3-pip ruby -y
    - name: install gazer
      command: sudo gem install gazer
    - name: install henry and looker deployer
      command: pip install henry looker_deployer


