instance_name = "looker-ps-toolkit-gcmarc"
project_id = "githublookertoolkittest"
zone = "europe-west3-c"
region = "europe-west3"
machine_type = "f1-micro"
sa_email = "looker-toolkit@githublookertoolkittest.iam.gserviceaccount.com"
